### PR TITLE
Query.js: Added `limit` and `cursor`

### PR DESCRIPTION
**Pull request by mpneuried**
I created a first version to solve your To do: _Add method to specify Limit and ExclusiveStartKey_
Can you have a took at it and tell me your opinion?

### CODE REVIEW

**Comment by mpneuried** [comment]
Hello Jed,

i also added a fix for correct handling of `Action:"Delete"` on Dynamo sets

**Comment by mpneuried** [comment]
Next change ;-)
I added the `limit` and (now) `startAt` methods to Scan.js, too.

**Comment by jed** [comment]
thanks @mpneuried! i'm headed on vacation for the next week, but will check on these when i get back, okay?

**Comment by mpneuried** [comment]
Hi @jed. I wish you a relaxing vacation. Don't hurry ;-)

I'm in heavy development for my abstraction. So if i find some bugs or do some changes to your module, i will update this pull request.

**Comment by mpneuried** [comment]
As i promised ... here comes the next change. I added options + the option `returnvalues` to the `item.destroy( [options], callback )`. Now it's possible to define the `Returnvalues` key for the AWS `DeleteItem` request.

**Comment by mpneuried** [comment]
Next update. I found a bug in `Batch.js`. The check for `UnprocessedKeys` was true on a empty object. So the module tried a second empty  call which produced an error.

**Pull request closed without merging**
